import { cn } from "@/lib/utils"
import { dir } from "i18next"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { languages } from "../i18n/settings"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode
  params: { lng: string }
}>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={cn(inter.className, "flex flex-col min-h-screen")}>
        <main>{children}</main>
      </body>
    </html>
  )
}
